### ISSUE TITLE
Add project to OPA ecosystem listing

### ISSUE THREAD

**Issue by anderseknert** [Snowflake-Labs/sansshell#106]
Not an issue really, but just found out about this project and I love the idea! 😃 

Would you consider adding this integration to the OPA [ecosystem](https://www.openpolicyagent.org/docs/latest/ecosystem/) page? (there's a link top-right for how to add an entry)

Also, definitely would welcome a PR to have it added to the [Awseome OPA](https://github.com/anderseknert/awesome-opa) list.

Thanks!

**Comment by sfc-gh-jchacon** [comment]
https://github.com/open-policy-agent/opa/pull/4674 is the PR to add to the ecosystem page.

Can I add you as the signoff to pass the merge gate test?
